.github/workflows/api-deploy-stg.yml

NAVEGA_API_URL

---

.github/workflows/monorepo-api-deploy-aws-dev.yml
.github/workflows/monorepo-quality-api-workflow.yml

insert build step
Atividade # https://f3c.atlassian.net/browse/RMD-40
NA

insert build step

---

.github/workflows/monorepo-api-deploy-aws-prd.yml
.github/workflows/monorepo-api-deploy-aws-sbx.yml
.github/workflows/monorepo-api-deploy-aws-stg.yml

monorepo-api-deploy

---

.github/workflows/lib-monorepo-deploy-main.yml

update monorepo lib deploy

---

.github/workflows/api-deploy-aws-dev-with-layers.yml

Adicionei uma nova configuração de pipeline que instala as dependencias do projeto e tbm qualquer layer que exista dentro do repositorio.
Atividade # (ID)[link]

chore: add new workflow deploy with layer

---

.github/workflows/api-deploy-portal-dev-with-layers.yml
.github/workflows/api-deploy-portal-prd-with-layers.yml
.github/workflows/api-deploy-portal-sbx-with-layers.yml
.github/workflows/api-deploy-portal-stg-with-layers.yml

Criação de novos workflows para deploy nos ambientes do portal, com as configurações necessárias para instalação de pacotes utilizando layers
Atividade # [OC-1469](https://f3c.atlassian.net/browse/OC-1468?atlOrigin=eyJpIjoiODVjZDY5Mjc4YTllNDRkMjlmZjQzNDM4NmUxNTAxYTMiLCJwIjoiaiJ9)
[OC-1469]: https://f3c.atlassian.net/browse/OC-1469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(OC-1469): create new workflows with lambda layers installments settings

---

.github/workflows/api-deploy-aws-dev.yml
.github/workflows/api-deploy-aws-prd.yml
.github/workflows/api-deploy-aws-sbx.yml
.github/workflows/api-deploy-aws-stg.yml
.github/workflows/api-deploy-portal-dev.yml
.github/workflows/api-deploy-portal-prd.yml
.github/workflows/api-deploy-portal-sbx.yml
.github/workflows/api-deploy-portal-stg.yml

Adequando os pipelines com as Configurações de lambda layer 
Atividade # [ARQ-34](https://f3c.atlassian.net/browse/ARQ-34)
[ARQ-34]: https://f3c.atlassian.net/browse/ARQ-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: adjustments pipelines with lambda layer config

---

.github/workflows/api-deploy-aws-dev-with-layers.yml
.github/workflows/api-deploy-aws-dev.yml
.github/workflows/api-deploy-aws-prd-with-layers.yml
.github/workflows/api-deploy-aws-prd.yml
.github/workflows/api-deploy-aws-sbx-with-layers.yml
.github/workflows/api-deploy-aws-sbx.yml
.github/workflows/api-deploy-aws-stg-with-layers.yml
.github/workflows/api-deploy-aws-stg.yml
.github/workflows/api-deploy-portal-dev.yml
.github/workflows/api-deploy-portal-prd.yml
.github/workflows/api-deploy-portal-sbx.yml
.github/workflows/api-deploy-portal-stg.yml
.github/workflows/monorepo-api-deploy-aws-dev.yml
.github/workflows/monorepo-api-deploy-aws-prd.yml
.github/workflows/monorepo-api-deploy-aws-sbx.yml
.github/workflows/monorepo-api-deploy-aws-stg.yml

forçar a versao 3 na instalacao do serveless
Atividade # (ID)[link]

set serverless to version 3

---

.github/workflows/lib-deploy-main.yml

Atividade # [9709](https://dev.azure.com/Quandoprev/Tecnologia/_workitems/edit/9709)

chore: ignore dev dev dependencies

---

.github/workflows/api-deploy-aws-dev.yml
.github/workflows/api-deploy-aws-prd.yml
.github/workflows/api-deploy-aws-sbx.yml
.github/workflows/api-deploy-aws-stg.yml
.github/workflows/quality-security-workflow.yml

- atualizacao da versao do node para 20

upgrade node version

---

.github/workflows/api-deploy-aws-dev.yml
.github/workflows/api-deploy-aws-prd.yml
.github/workflows/api-deploy-aws-sbx.yml
.github/workflows/api-deploy-aws-stg.yml

Add env use_atlas_api on deploy

---

.github/workflows/api-deploy-aws-dev-with-layers.yml
.github/workflows/api-deploy-aws-dev.yml
.github/workflows/api-deploy-aws-prd-with-layers.yml
.github/workflows/api-deploy-aws-prd.yml
.github/workflows/api-deploy-aws-sbx-with-layers.yml
.github/workflows/api-deploy-aws-sbx.yml
.github/workflows/api-deploy-aws-stg-with-layers.yml
.github/workflows/api-deploy-aws-stg.yml
.github/workflows/api-deploy-portal-dev.yml
.github/workflows/api-deploy-portal-prd.yml
.github/workflows/api-deploy-portal-sbx.yml
.github/workflows/api-deploy-portal-stg.yml
.github/workflows/lib-deploy-main.yml
.github/workflows/lib-monorepo-deploy-main.yml
.github/workflows/monorepo-api-deploy-aws-dev.yml
.github/workflows/monorepo-api-deploy-aws-prd.yml
.github/workflows/monorepo-api-deploy-aws-sbx.yml
.github/workflows/monorepo-api-deploy-aws-stg.yml
.github/workflows/monorepo-quality-api-workflow.yml
.github/workflows/navega-libs-deploy-main.yml
.github/workflows/navega-libs-quality-security-workflow.yml
.github/workflows/quality-portal-api-workflow.yml
.github/workflows/quality-security-monorepo-workflow.yml
.github/workflows/quality-security-portal-api-workflow.yml
.github/workflows/quality-workflow.yml

Migração de tudo que é yarn para npm.
Exceção arquivo do web

Yarn to Npm

---

.github/workflows/api-deploy-aws-dev-with-layers.yml
.github/workflows/api-deploy-aws-dev.yml
.github/workflows/api-deploy-aws-prd-with-layers.yml
.github/workflows/api-deploy-aws-prd.yml
.github/workflows/api-deploy-aws-sbx-with-layers.yml
.github/workflows/api-deploy-aws-sbx.yml
.github/workflows/api-deploy-aws-stg-with-layers.yml
.github/workflows/api-deploy-aws-stg.yml
.github/workflows/api-deploy-portal-dev.yml
.github/workflows/api-deploy-portal-prd.yml
.github/workflows/api-deploy-portal-sbx.yml
.github/workflows/api-deploy-portal-stg.yml
.github/workflows/lib-deploy-main.yml
.github/workflows/lib-monorepo-deploy-main.yml
.github/workflows/monorepo-api-deploy-aws-dev.yml
.github/workflows/monorepo-api-deploy-aws-prd.yml
.github/workflows/monorepo-api-deploy-aws-sbx.yml
.github/workflows/monorepo-api-deploy-aws-stg.yml
.github/workflows/monorepo-quality-api-workflow.yml
.github/workflows/navega-libs-deploy-main.yml
.github/workflows/navega-libs-quality-security-workflow.yml
.github/workflows/quality-portal-api-workflow.yml
.github/workflows/quality-security-monorepo-workflow.yml
.github/workflows/quality-security-workflow.yml

chore: change npm to yarn

---

.github/workflows/api-deploy-aws-dev.yml
.github/workflows/api-deploy-aws-prd.yml
.github/workflows/api-deploy-aws-sbx.yml
.github/workflows/api-deploy-aws-stg.yml

chore: Update dev, sbx, and stg deployment workflows

---

.github/workflows/monorepo-quality-api-workflow.yml
.github/workflows/navega-libs-quality-security-workflow.yml
.github/workflows/quality-security-monorepo-workflow.yml
.github/workflows/quality-security-portal-api-workflow.yml
.github/workflows/quality-security-portal-web-workflow.yml
.github/workflows/quality-security-workflow-with-npm.yml
.github/workflows/quality-security-workflow.yml

upgrade to v4

---

.github/workflows/quality-security-workflow.yml

add npm config fix

---

.github/workflows/quality-security-workflow.yml

add config fix before install

---

.github/workflows/monorepo-quality-api-workflow.yml
.github/workflows/navega-libs-quality-security-workflow.yml
.github/workflows/quality-security-monorepo-workflow.yml
.github/workflows/quality-security-workflow.yml
.github/workflows/quality-workflow.yml

chore: install libcrypto befores tests

chore: install libcrypto befores tests

---

.github/workflows/quality-ai-pr-review-workflow.yml

Este PR adiciona um novo workflow reutilizável chamado quality-pr-review-ai-workflow.yml para realizar revisão automatizada de código em Pull Requests utilizando Amazon Bedrock.
O objetivo é garantir uma análise automatizada do código enviado via PRs, fornecendo sugestões de melhoria, detecção de possíveis problemas e reforço das boas práticas de desenvolvimento.
1 - Criar um novo Pull Request para as branchs configuradas nas triggers.
2 - O workflow deve ser acionado automaticamente.
3 - A revisão automática do código será feita pelo Amazon Bedrock.
4 - O bot de revisão deve adicionar comentários no PR caso detecte sugestões ou melhorias.

Add Reusable AI-Powered Code Review Workflow for Pull Requests

---

.github/workflows/api-deploy-aws-dev.yml
.github/workflows/api-deploy-aws-prd.yml
.github/workflows/api-deploy-aws-pre-sbx.yml
.github/workflows/api-deploy-aws-sbx.yml
.github/workflows/api-deploy-aws-stg.yml

Add WARMUP_ENABLED environment variable to deployment workflows

---

.github/workflows/api-deploy-aws-prd.yml
.github/workflows/api-deploy-aws-sbx.yml
.github/workflows/monorepo-api-deploy-aws-prd.yml
.github/workflows/monorepo-api-deploy-aws-sbx.yml

Add AWS_LAMBDA_EXEC_WRAPPER environment variable to deployment workflows
